services:
  - type: web
    name: lumixly-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PROCESSING_API_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
